ENV['VAGRANT_NO_PARALLEL'] = 'yes'
IMAGE_NAME = "centos/7"

##########################
##### USER SETTINGS  #####
##########################
N_Instances = 2
NETWORK = "170.10.10"
GREMLIN_TEAM_ID = "*******"
GREMLIN_TEAM_SECRET = "*******"
##########################
##########################

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    #VBox shared folder definition
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    #VBguest plugin install if not present
    config.vagrant.plugins = {"vagrant-vbguest" => {"version" => "0.30.0"}}
    #From VBGuest >0.22 allow_kernel_upgrade is needed
    config.vbguest.installer_options = { allow_kernel_upgrade: true }

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end

    # Setup of K8s Worker nodes
    (1..N_Instances).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "#{NETWORK}.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "node-playbook.yml"
                ansible.extra_vars = {
                    gremlin_team_id: GREMLIN_TEAM_ID,
                    gremlin_team_secret: GREMLIN_TEAM_SECRET,
                    gremlin_identifier: "#{NETWORK}.#{i + 10}"
                }
            end
        
        end
    end
   
end
